#
# Author: Tre King
# Github: ha-king
#
AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS - Cluster

Parameters:
  ClusterName:
    Type: String
    Description: Name of the EKS cluster
    Default: 'EKS-DEV2'
  EksVersion:
    Type: String
    Description: Name of the EKS cluster
    Default: '1.23'
  KeyName:
    Type: String
    Description: Name of the EC2 ssh keypair name for node workders
    Default: 'eks-workers'

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, '']]

Resources:
  EksClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "eks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
 
  EksNodeWorkerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Policies:
        -
          PolicyName: "policy-for-eks-rbac"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "eks:ListClusters"
                  - "eks:DescribeClusters"
                Resource:
                  - "*"

  NodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - Ref: EksNodeWorkerRole
        
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Ref ClusterName
      Version: !Ref EksVersion
      RoleArn: !GetAtt ["EksClusterRole", "Arn"]
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-03bbd61ed49f6ff22
        SubnetIds:
        - subnet-0d6e6bac51c3ee655
        - subnet-058e54b2ecc1376fc

  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    DependsOn: "EKSCluster"
    Properties:
      AmiType: AL2_x86_64
      ClusterName: !Ref ClusterName
      DiskSize: 20
      ForceUpdateEnabled: true
      InstanceTypes:
        - t3.medium
      NodegroupName: !Sub "${AWS::StackName}-nodegroup"
      NodeRole: !Ref EksNodeWorkerRole
      RemoteAccess:
        Ec2SshKey: !If [HasKeyName, !Ref KeyName, !Ref 'AWS::NoValue']
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 4
      Subnets:
        - subnet-0d6e6bac51c3ee655
        - subnet-058e54b2ecc1376fc
        - subnet-0f1b586c0cca62fa7
        - subnet-0a4ffdb5928cdc0e5
