kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-NAMESPACE-rolebinding
  namespace: NAMESPACE
subjects:
- kind: User
  name: k8s-NAMESPACE-user
roleRef:
  kind: Role
  name: k8s-NAMESPACE-role
  apiGroup: rbac.authorization.k8s.io